services:
  - type: web
    name: natours
    runtime: node
    plan: free
    buildCommand: NPM_CONFIG_PRODUCTION=false npm ci && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: "20.18.0"
      - key: NPM_CONFIG_PRODUCTION
        value: "false"
      - key: NODE_ENV
        value: production
      - key: DATABASE
        sync: false
      - key: DATABASE_PASSWORD
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRES_IN
        value: 90d
      - key: JWT_COOKIE_EXPIRES_IN
        value: 90
      - key: EMAIL_FROM
        sync: false
      - key: EMAIL_HOST
        sync: false
      - key: EMAIL_PORT
        sync: false
      - key: EMAIL_USERNAME
        sync: false
      - key: EMAIL_PASSWORD
        sync: false
      - key: YANDEX_MAPS_KEY
        sync: false
      - key: YOOKASSA_SHOP_ID
        sync: false
      - key: YOOKASSA_SECRET_KEY
        sync: false
      - key: YOOKASSA_WEBHOOK_SECRET
        sync: false
